### ISSUE TITLE
Reversed backpack with glasses

### ISSUE THREAD

**Issue by CanntReport** [Nova-Committee/Glasses#1]
![2024-02-21_22 42 25](https://github.com/Nova-Committee/Glasses/assets/133471431/4884bea2-9ef0-46e0-945f-a8c99cc4f07c)

When I wear glasses and backpack from Sophisticated Backpacks,the backpack will be reversed(seems like in picture)
当我同时佩戴模组里的任一眼镜和精妙背包里的任何背包时，背包会倒过来,如图所示。
game version:1.20.1
mods version:1.2.3
Sophisticated Backpacks version:3.19.8.1000

**Comment by VulpesStella** [comment]
已在 Forge-1.20.1-1.2.5 修复，其他版本跟进中。
